from __future__ import annotations

from typing import Literal

UNSUPPORTED_ARTIFACT_VERSION = "UNSUPPORTED_ARTIFACT_VERSION"
MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_TYPE = "INVALID_TYPE"
INVALID_VALUE = "INVALID_VALUE"
MISSING_REQUIRED_TAG = "MISSING_REQUIRED_TAG"
DRAFT_CONTAINS_SIGNED_FIELDS = "DRAFT_CONTAINS_SIGNED_FIELDS"
SIGNED_MISSING_SIGNATURE_FIELDS = "SIGNED_MISSING_SIGNATURE_FIELDS"
UNSUPPORTED_EVENT_KIND = "UNSUPPORTED_EVENT_KIND"
INVALID_JSON = "INVALID_JSON"

ALL_ERROR_CODES: tuple[str, ...] = (
    UNSUPPORTED_ARTIFACT_VERSION,
    MISSING_REQUIRED_FIELD,
    INVALID_TYPE,
    INVALID_VALUE,
    MISSING_REQUIRED_TAG,
    DRAFT_CONTAINS_SIGNED_FIELDS,
    SIGNED_MISSING_SIGNATURE_FIELDS,
    UNSUPPORTED_EVENT_KIND,
    INVALID_JSON,
)

ErrorCode = Literal[
    "UNSUPPORTED_ARTIFACT_VERSION",
    "MISSING_REQUIRED_FIELD",
    "INVALID_TYPE",
    "INVALID_VALUE",
    "MISSING_REQUIRED_TAG",
    "DRAFT_CONTAINS_SIGNED_FIELDS",
    "SIGNED_MISSING_SIGNATURE_FIELDS",
    "UNSUPPORTED_EVENT_KIND",
    "INVALID_JSON",
]
